### ISSUE TITLE
3DS-Recovery-Tool freezes upon loading

### ISSUE THREAD

**Issue by VeteranJaime** [joel16/3DS-Tool#2]
currently experiencing an issue with 3DS-Recovery-Tool when, upon loading the application up, it loads on the homebrew splash screen animation, then freezes.

**Comment by joel16** [comment]
I haven't messed with this code in years. I'll see what I can do.

**Comment by joel16** [comment]
Are you using a .3dsx or .CIA? I can send you a test build with the most recent up-to-date changes.

**Comment by VeteranJaime** [comment]
> Are you using a .3dsx or .CIA? I can send you a test build with the most recent up-to-date changes.

Using the .CIA version.

**Comment by joel16** [comment]
Could you build and test the latest commit? Otherwise you'll have to wait till I get off of work.

**Comment by VeteranJaime** [comment]
> Could you build and test the latest commit? Otherwise you'll have to wait till I get off of work.

i´ll attempt it. but if it does not work, i´ll let you know.

**Comment by joel16** [comment]
Here's a compiled CIA build https://drive.google.com/open?id=11BzLiQErLjo9hlCWAkx1eDJ4bKAAs1ij

**Comment by VeteranJaime** [comment]
the compiled cia build worked! thanks for helping me with this issue! :)

**Comment by joel16** [comment]
Thank you for confirming! Fixed with https://github.com/joel16/3DS-Recovery-Tool/commit/960e0fee327b90b158cd50bae5953b6dd3c43120.
